apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsd-project
  labels:
    app: fsd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fsd-project
  template:
    metadata:
      labels:
        app: fsd-project
    spec:
      containers:
      - name: fsd-project
        image: docker.io/abhimanyu221106/devops-project:latest
        ports:
        - containerPort: 80
